name: json_at

description: >
      Dart implementation of RFC 6901 JSON pointer specification .

version: 2.0.0-nullsafety.1
author: Adamansky Anton <adamansky@softmotions.com>

homepage: 'https://github.com/Softmotions/json_at'
repository: 'https://github.com/Softmotions/json_at'
issue_tracker: 'https://github.com/Softmotions/json_at/issues'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  test: ^1.16.0-nullsafety.13
  quiver: ^3.0.0-nullsafety.2
