name: json_at

description: >
      Dart implementation of RFC 6901 JSON pointer specification .


version: 1.0.2
author: Adamansky Anton <adamansky@softmotions.com>

homepage: 'https://github.com/Softmotions/json_at'
repository: 'https://github.com/Softmotions/json_at'
issue_tracker: 'https://github.com/Softmotions/json_at/issues'

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  test: ^1.6.5
  quiver: ^2.0.3
