name: json_at

description: >
      Dart implementation of RFC 6901 JSON pointer specification .

version: 2.1.0

homepage: 'https://github.com/Softmotions/json_at'
repository: 'https://github.com/Softmotions/json_at'
issue_tracker: 'https://github.com/Softmotions/json_at/issues'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  test: ^1.17.8
  quiver: ^3.0.1
